name: wifi_scanner
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: 0.7.0+2
  simple_permissions: ^0.1.9

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test: 
    sdk: flutter 

flutter: 
  uses-material-design: true
