name: wifi_scanner
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # connectivity: ^0.4.5+1
  cupertino_icons: ^0.1.2
  device_info: 0.4.0+1
  equatable: ^0.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^1.0.0
  # geolocator: ^5.1.4+2
  http: 0.12.0+2
  logger: 0.7.0+2
  path_provider: ^1.4.0
  simple_permissions: ^0.1.9 
  sqflite: ^1.1.7+1

dev_dependencies:
  flutter_test: 
    sdk: flutter 

flutter: 
  uses-material-design: true
